spring:
  liquibase:
    change-log: classpath:changeSets/databaseChangeLog.xml
  application:
    name: restApi
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/goods_db?createDatabaseIfNotExist=true&useLegacyDatetimeCode=false&serverTimezone=UTC&useSSL=false&nullNamePatternMatchesAll=true
    username: root
    password: dep16215675
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      javax:
        persistence:
          validation:
            mode: none
      hibernate:
        show_sql: true
        format_sql: true
        dialect:                       org.hibernate.dialect.MySQL5Dialect
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
logging:
  level:
    org.springframework: info
    com.itsm.pub.courses.patients: debug